trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install pytest playwright
    pip install pytest-html
    playwright install
  displayName: 'Install dependencies'

- script: mkdir -p reports
  displayName: 'Create reports directory'

- script: |
    python test_example_ignore_ssl.py --html=reports/report.html --self-contained-html
  displayName: 'Run tests and generate HTML report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'playwright-html-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'


