
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "10.0.0.12 https://mms.uat.exyte.net" | sudo tee -a /etc/hosts
    cat /etc/hosts
  displayName: 'Add hosts mapping'

- script: |
    pip install --upgrade pip
    pip install pytest playwright pytest-playwright pytest-html
    playwright install --with-deps
    pytest --base-url https://mms.uat.exyte.net
  displayName: 'Install dependencies and Playwright browsers'

- script: |
    mkdir -p reports
    pytest test_example_ignore_ssl.py --html=reports/report.html --self-contained-html
  displayName: 'Run tests and generate HTML report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'playwright-html-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'

