
trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals EXYDAPPWEB01

variables:
  - group: GitSSHSecrets

steps:
- script: |
    mkdir -p ~/.ssh
    echo "$(SSH_PRIVATE_KEY)" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    git clone git@github.com:your-org/your-repo.git
  displayName: 'Clone Git Repo via SSH'

#- script: |
#    echo "10.0.0.12 mms.uat.exyte.net" | sudo tee -a /etc/hosts
#    cat /etc/hosts
#  displayName: 'Add hosts mapping'
#
#- script: |
#    unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy
#    export NO_PROXY="mms.uat.exyte.net,.exyte.net,127.0.0.1,localhost"
#    echo "NO_PROXY=$NO_PROXY"
#  displayName: 'Disable proxy for UAT host'

- script: |
    pip install --upgrade pip
    pip install pytest playwright pytest-playwright pytest-html
    playwright install --with-deps
  displayName: 'Install dependencies and Playwright browsers'

- script: |
    mkdir -p reports
    pytest test_example_ignore_ssl.py --html=reports/report.html --self-contained-html
  displayName: 'Run tests and generate HTML report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'playwright-html-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'

