
trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals EXYDAPPWEB01

variables:
  - group: GitSSHSecrets

steps:
- checkout: none

- powershell: |
    $sshDir = "$env:USERPROFILE\.ssh"
    if (!(Test-Path -Path $sshDir)) {
        New-Item -ItemType Directory -Path $sshDir | Out-Null
    }

    $privateKeyPath = "$sshDir\id_rsa"

    # 写入 SSH 私钥
    $privateKey = $env:SSH_PRIVATE_KEY -replace "`r`n", "`n"
    Set-Content -Path $privateKeyPath -Value $privateKey -Encoding ascii
    icacls $privateKeyPath /inheritance:r
    icacls $privateKeyPath /grant:r "$env:USERNAME:R"
    icacls $privateKeyPath /grant:r "$env:USERNAME:W"
    icacls $privateKeyPath /grant:r "$env:USERNAME:RX"

    # 添加 Git 服务器到 known_hosts
    ssh-keyscan github.com >> "$sshDir\known_hosts"

    # 克隆仓库
    git@github.com:Zhuang5-Edison/Azure-pipline-pytest_playwright.git
  displayName: 'Clone Git Repo via SSH'



#- script: |
#    echo "10.0.0.12 mms.uat.exyte.net" | sudo tee -a /etc/hosts
#    cat /etc/hosts
#  displayName: 'Add hosts mapping'
#
#- script: |
#    unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy
#    export NO_PROXY="mms.uat.exyte.net,.exyte.net,127.0.0.1,localhost"
#    echo "NO_PROXY=$NO_PROXY"
#  displayName: 'Disable proxy for UAT host'

- script: |
    pip install --upgrade pip
    pip install pytest playwright pytest-playwright pytest-html
    playwright install --with-deps
  displayName: 'Install dependencies and Playwright browsers'

- script: |
    mkdir -p reports
    pytest test_example_ignore_ssl.py --html=reports/report.html --self-contained-html
  displayName: 'Run tests and generate HTML report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'playwright-html-report'
    publishLocation: 'pipeline'
  displayName: 'Publish HTML Test Report'

